name: Code Formatter
on:
  pull_request:
    types:
      - labeled
jobs:
  autoformat:
    runs-on: ubuntu-latest
    if: contains( github.event.pull_request.labels.*.name, 'autoformat')
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.14'
      - name: Install goimports
        run: go get golang.org/x/tools/cmd/goimports
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - run: goimports -w .
      - run: go mod tidy
      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # TODO: check this is not a fork.
        run: |
          git config user.name tbpg
          git config user.email 26876514+tbpg@users.noreply.github.com
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git add .
          if [ -n "$(git status --porcelain)" ]; then
            git commit --author "tbpg[bot] <26876514+tbpg@users.noreply.github.com>" --message "Run goimports and go mod tidy"
            git push
          fi
      - name: Remove autoformat label
        uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.removeLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              name: 'autoformat'
            })
      - name: Trigger lint and test
        uses: actions/github-script@v2
        with:
          github-token: ${{secrets.FORMAT_TOKEN}}
          script: |
            github.repos.createDispatchEvent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              event_type: 'autoformat'
            });
